github/details-dialog-element

index.css
index.js
package-lock.json
test/test.js

Removes the automatically added close button in favor or allowing implementors to supply their own. Originally it did this:
> Fixes #10 by checking for whether a close button (`[data-close-dialog]`) exists in the DOM before adding one automatically. There's a simple test for it, which passes! 🎉
But after some discussion, we agreed that nixing the close button altogether was the best move.
I've also introduced `CLOSE_ATTR`, `CLOSE_SELECTOR`, and `INPUT_SELECTOR` constants to keep things dry, and exposed them as static members of the (now `default`-exported) custom element class, which means that you can do this in other modules, e.g. in React:
```js
import DetailsDialog from 'details-dialog-element'
import React from 'react'
const closeProps = {
[DetailsDialog.CLOSE_ATTR]: true
}
export …
```

Don't create a close button automatically

---

index.js

We have other details event listeners using capture due do event delegation, these ones aren't. I'm removing them to avoid future confusion.
cc @dgraham I'll do a release after this, do you think #11 deserve a major version bump?

Remove capture

---

index.css

This pull request sets a `max-width` of `90vw` on the dialogs so they don't become wider than the screen on narrow screens.
| Before | After |
| --- | --- |
| <img width="580" alt="screen shot 2018-07-20 at 10 28 28 am" src="https://user-images.githubusercontent.com/671378/43016493-e0f1a6c2-8c07-11e8-9f65-89ecb23ad6fd.png">|<img width="580" alt="screen shot 2018-07-20 at 10 27 58 am" src="https://user-images.githubusercontent.com/671378/43016491-de2c2214-8c07-11e8-9413-cb566e2f2edb.png"> |
/cc @jonrohan since we were discussing this a bit yesterday

Add max width set to 90vw

---

index.js

Bug introduced in #16. When tab is trapped, the `<summary>` element outside the dialog was being focused on, because `event.currenTarget` is actually `<details>` not `<details-dialog>`. This change makes sure we query inside of `details-dialog` instead of `details`.

Fix querying focusable elements

---

index.html
index.js

It's been tricky trying to work around the event order of returning focus on `esc` from outside of details-dialog code. So I changed the code here to return focus to `activeElement` (in most case it'd be `summary`) instead of querying directly for `summary`.
I'd have added tests for this but looks `activeElement` is always `body` unless `focus` is called directly on elements. 🤔

Escape event boundary + focus return to activeElement

---

index.js
test/test.js

This pull request changes the toggling of the dialog to click the `<summary>` element instead of directly setting the `open` attribute on the `<details>` element.
This allows listeners to listen to the `click` event on the `<summary>` and prevent it so the dialog will not close.
The plan is to use this to add some confirm on close behavior so that closing the dialog can be aborted if the user does not confirm they want to discard unsaved changes to the form inside the dialog.

Click summary to close dialog so it can be canceled

---

README.md
index.js
test/test.js

Adds a `details-dialog:will-close` event when the summary is clicked that can be cancelled to prevent the dialog from closing.
Refs https://github.com/github/details-dialog-element/pull/21#pullrequestreview-155152495

Add cancellable details-dialog:will-close event

---

index.js
test/test.js

- Add tests for tab trapping
- Check if parent element is hidden in `focusable()`
- Fix starting focus target index (previously the first element to focus was the last one)
- Prevent error being thrown when nothing is focusable in a dialog

Consider hidden parent element in focus management

---

.babelrc
.eslintrc.json
README.md
package-lock.json
package.json
test/.eslintrc.json

Reduce the size of the distribution by not transforming the `class` keyword. Dropped IE11 support in the meanwhile and updated some packages.

Remove classes transform

---

index.js

I'm using this under the full WebComponents polyfill,
plus a polyfill for `.closest`.

Fix the escape key when running under IE11

---

index.js

Resolves #26. 
References: 
- [`delegatesFocus`](https://github.com/w3c/webcomponents/issues/802#issuecomment-477793868) is only supported in Chrome with an unclear future 😓 .
- Use of `tabIndex` https://github.com/whatwg/html/issues/4464, note how `delegatesFocus` host has `tabIndex` of 0 in Chrome.
cc @bennypowers

Update query for focusable elements

---

index.js

Found two issues while upgrading:
1. on mouseover `preload` triggers and `autofocus` is called even though dialog is still closed
2. removing `preload` attribute while `src` is present does not remove the event listener because `removeEventListener` is only called when `this.src` is falsey.

Fix autofocusing when details is not open & preload toggling

---

index.js

I didn't add [`aria-modal`](https://www.w3.org/TR/wai-aria-1.1/#aria-modal) previously because the browser support was questionable. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=716592 to Chrome 2 years ago, but there hasn't been progress. Testing showed that this at least works with Safari in with VoiceOver.

Add aria-modal

---

index.html

Since the package has been published under the `@github` scope,
I have updated the `index.html` file in order to reference to the right unpkg URL.
ref: #36

Update index.html by importing the latest version from unpkg

---

index.js

This conflicts with `<details-menu>`'s role requirement.

Avoid setting role attribute if attribute is present

---

index.js
test/test.js

fixes #38 
The order of connectedCallback and attributesChangedCallback is not guaranteed, so the event listeners for include fragment has to be added in the connectedCallback as well.
Also the event listeners will be removed in the disconnectedCallback.

Fix dialog with include fragment

---

index.js.flow

Fixes an error importing the class.
```js
import DetailsDialogElement from '@github/details-dialog-element
```
> Error: Importing from an untyped module makes it `any` and is not safe!

Include module in Flow declaration

---

index.js
test/test.js

Fixes #41, refer to considerations in https://github.com/github/details-dialog-element/issues/41#issuecomment-512864096.
This is a reliable visibility check (which comes with a perf cost as it triggers layout). I kept `.hidden` and `type=hidden` checks because they're relatively cheap and we use them often. When they were true we skip some `visible` calls.
Example use case:
```html
<details-dialog>
<details>
<details-menu><button></button></details-menu>
</details>
</details-dialog>
```
and for autofocus:
```html
<details-dialog>
<details>
<details-menu><input autofocus></details-menu>
</details>
<button autofocus></button>
</details-dialog>
```

Ensure focusble targets are visible

---

index.js
test/test.js

I will comment inline to point out where the bugs come from.
Bonus: instead of `.initEvent` this updates the test to use the proper event class constructors.

Fix shift tab when currentIndex is 0 or -1

---

index.js
test/test.js

The old check looks for the existence of the closest open details, which might not be the closest details. This changes it to look for the closest details, and then check if it is open. I think it reads better than checking if the closest open details is the closest details.
I've also changed the test markup be in a nested details, in case if this causes an issue again.
🙆🏻 
cc @mxie @elbrenn

Fix nested details misfiring close events

---

src/index.css

Make sure that the dialog is scrollable when the dialog is larger than the display. You can test out this change on the example page by making the browser window smaller in height than the dialog. See the example section for examples.
https://user-images.githubusercontent.com/318208/133088892-19069f03-530e-471b-b6b3-f7d714269d2f.mov
https://user-images.githubusercontent.com/318208/133088899-d3b4e484-fd2c-494b-8a75-c0445112d0ae.mov

Make sure to scroll any overflow

---

test/test.js

We should fix this test, but skipping for now as the solution is a bit involved.
Tracked in https://github.com/github/details-dialog-element/issues/77 which has some notes about what the problem is.

Skip failing test for managing focus

---

src/index.ts
test/test.js

When the `<details-dialog>` element is connected to the document as a
child of a `<details>` element rendered with `[open]`, trap focus
immediately.
In support of this change, extract the `trapFocus` and `releaseFocus`
functions, then call `trapFocus` within the `connectedCallback` if the
ancestor detail is `[open]`.

Trap focus when connected in `<details open>`
